swagger: "2.0"
info:
  version: "1.0.0"
  title: "API"
basePath: "/jangan/v1/user"

tags:
  - name: app
    description: Endpoints for app

paths:
  /signup:
    post:
      summary: "This web service allows user to register with email"
      tags:
        - app
      produces:
        - "application/json"
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                required: true
                type: string
                example: "ajai1@yopmail.com"
              password:
                required: true
                type: string
                example: "Ajai@123"
              isPrivacyAccepted:
                required: true
                type: boolean
                example: true  
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/signup"
  /register/phone:
    post:
      summary: "This web service allows user to register phone"
      tags:
        - app
      produces:
        - "application/json"
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              _id:
                required: true
                type: string
                example: "608960551fdd8d5d6bc93841"
              phoneNumber:
                required: true
                type: string
                example: "8010992020"
              countryCode:
                required: true
                type: string
                example: "+91"    
      responses:
        200:
          description: "OTP sent successfully"
          schema:
            $ref: "#/definitions/registerPhone"
  /verify/phone:
    post:
      summary: "This web service allows user to verify phone number"
      tags:
        - app
      produces:
        - "application/json"
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              otp:
                required: true
                type: string
                example: "5535"
              phoneNumber:
                required: true
                type: string
                example: "8010992020"
      responses:
        200:
          description: "Phone Verification"
          schema:
            $ref: "#/definitions/verifyPhone"
        401:
          description: "OTP Expired"
          schema:
            $ref: "#/definitions/verifyPhoneExpired"
        404:
          description: "User Not Found"
          schema:
            $ref: "#/definitions/verifyPhoneNotFound" 
  /otp:
    post:
      summary: "This web service allows user to resend otp "
      tags:
        - app
      produces:
        - "application/json"
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              phoneNumber:
                required: true
                type: string
                example: "8010992020"
              countryCode:
                required: true
                type: string
                example: "+91"    
      responses:
        200:
          description: "OTP sent successfully"
          schema:
            $ref: "#/definitions/resendOtp"    
  
definitions:
  Timestamp:
    type: object
    properties:
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
  signup:
    allOf:
      - $ref: "#/definitions/signup"
      - type: object
        properties:
          company:
            type: object
            example: {
              members : []
            }
          expectedChannelSpecifications:
            type: object
            example: {
              expectedChannels : [],
              selectedCountries : []
            }
          isPhysicalAddress:
            type: boolean
            example: false
          isBusinessAddressProofAdded:
            type: boolean
            example: false
          isAddressProofAdded:
            type: boolean
            example: false
          isEmailVerified:
            type: boolean
            example: false
          isPhoneVerified:
            type: boolean
            example: false
          createdAt:
            type: string
            example: "2021-06-07T05:34:06.293Z"
          updatedAt:
            type: string
            example: "2021-06-07T05:34:06.293Z"
          id:
            type: string
            example: "60bdafce3d667d55701df54a"
  registerPhone:
    allOf:
      - $ref: "#/definitions/registerPhone"
      - type: object
        properties:
          message:
            type: string
            example: "OTP sent successfully."
  verifyPhone:
    allOf:
      - $ref: "#/definitions/verifyPhone"
      - type: object
        properties:
          _id:
            type: string
            example: "60bdafce3d667d55701df54a"
          email:
            type: string
            example: "ajai12@yopmail.com"
          activationKey:
            type: string
            example: "487f7b22f68312d2c1bbc93b1aea445b"
          createdAt:
            type: string
            example: "2021-06-07T05:34:06.293Z"
          updatedAt:
            type: string
            example: "2021-06-07T05:34:06.293Z"
          id:
            type: string
            example: "60bdafce3d667d55701df54a"
          isEmailVerified:
            type: boolean
            example: false
          isPhoneVerified:
            type: boolean
            example: false
          countryCode:
            type: srting
            example: "+91"
          lastOtpRequestTime:
            type: srting
            example: "2021-06-07T08:09:35.734Z"
          otp:
            type: number
            example: 8263
          otpExpires:
            type: srting
            example: "2021-06-07T08:11:35.734Z"
          phoneNumber:
            type: number
            example: 8010992020
          accessToken:
            type: srting
            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFqYWkxMkB5b3BtYWlsLmNvbSIsIl9pZCI6IjYwYmRhZmNlM2Q2NjdkNTU3MDFkZjU0YSIsImlhdCI6MTYyMzA1MzM5MywiZXhwIjoxNjI1NDcyNTkzfQ.YyIAgYKu4HAeAQDAMUIpz5IJK4XS5z0Lsz865dau1g0"    
  resendOtp:
    allOf:
      - $ref: "#/definitions/resendOtp"
      - type: object
        properties:
          message:
            type: string
            example: "OTP sent successfully."       
  verifyPhoneExpired:
    allOf:
      - $ref: "#/definitions/verifyPhoneExpired"
      - type: object
        properties:
          error:
            type: object
            example: {
              code : 401,
              message : "otpExpiredOrWrongError",
            }
  verifyPhoneNotFound:
    allOf:
      - $ref: "#/definitions/verifyPhoneNotFound"
      - type: object
        properties:
          error:
            type: object
            example: {
              code : 404,
              message : "userNotFoundError",
            }                                                  
